name: Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Build a debug executable
      run: msbuild adeleg.sln /nologo /warnAsError /p:Configuration=Debug /p:Platform="Any CPU"
    - uses: actions/upload-artifact@v4
      with:
        name: executable
        path: |
          bin/Debug/adeleg.exe
          bin/Debug/adeleg.pdb
        if-no-files-found: error
